language: c

notifications:
  - email: true

# Install the cross-compiler
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf cmake
  - arm-linux-gnueabihf-gcc --version
  # Travis does 'export CC=gcc'. Unset CC so that ./flags.mk properly
  # defines the cross-compiler to the default value: $(CROSS_COMPILE)gcc.
  - unset CC

# Several compilation options are checked
script:
  - cd atsha204a
  - mkdir -p build && cd build
  - cmake -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc ..
  - make
