/*
 * Copyright 2017, Linaro Ltd and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __PERSONALIZE_H
#define __PERSONALIZE_H

/* Generated by ATSHA204A slot config generator */
struct slot_config {
     uint8_t address;
     uint8_t value[4];
};

#endif
