#include <stdbool.h>
#include <stdint.h>

#include <io.h>
#include <cmd.h>
#include <debug.h>
#include <personalize.h>
#include <status.h>

/* Generated by ATSHA204A slot config generator */
struct slot_config {
     uint8_t address;
     uint8_t value[4];
};

static struct slot_config slot_configs[] = {
	/* SlotConfig[0]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x08 */
	/* SlotConfig[1]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x0a */
	{ 0x05, {  0x80, 0x80,   0x80, 0xa0 } },

	/* SlotConfig[2]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x08 */
	/* SlotConfig[3]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x0b */
	{ 0x06, {  0x80, 0x80,   0x80, 0xb0 } },

	/* SlotConfig[4]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x08 */
	/* SlotConfig[5]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x0a */
	{ 0x07, {  0x80, 0x80,   0x80, 0xa0 } },

	/* SlotConfig[6]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x08 */
	/* SlotConfig[7]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x0b */
	{ 0x08, {  0x80, 0x80,   0x80, 0xb0 } },

	/* SlotConfig[8]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x08, WriteConfig=0x04 */
	/* SlotConfig[9]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=1, IsSecret=1, WriteKey=0x09, WriteConfig=0x04 */
	{ 0x09, {  0x80, 0x48,   0xc0, 0x49 } },

	/* SlotConfig[10]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x08 */
	/* SlotConfig[11]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=1, WriteKey=0x00, WriteConfig=0x08 */
	{ 0x0a, {  0x80, 0x80,   0x80, 0x80 } },

	/* SlotConfig[12]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=0, WriteKey=0x00, WriteConfig=0x00 */
	/* SlotConfig[13]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=0, WriteKey=0x00, WriteConfig=0x00 */
	{ 0x0b, {  0x00, 0x00,   0x00, 0x00 } },

	/* SlotConfig[14]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=0, WriteKey=0x00, WriteConfig=0x08 */
	/* SlotConfig[15]: ReadKey=0x00, CheckOnly=0, SingleUse=0, EncryptedRead=0, IsSecret=0, WriteKey=0x00, WriteConfig=0x08 */
	{ 0x0c, {  0x00, 0x80,   0x00, 0x80 } },
};

static bool is_configuration_locked(struct io_interface *ioif)
{
	uint8_t lock_data;
	int ret = cmd_get_lock_data(ioif, &lock_data);
	if (ret != STATUS_OK) {
		loge("Couldn't get lock data\n");
		return false;
	}

	return lock_data == LOCK_CONFIG_LOCKED;
}

int atsha204a_personalize(struct io_interface *ioif)
{
	int ret = STATUS_EXEC_ERROR;
	int i;

	if (is_configuration_locked(ioif)) {
		logd("Device already personalized\n");
		return STATUS_EXEC_ERROR;
	}

	/* Program the SlotConfigs */
	for (i = 0; i < sizeof(slot_configs) / sizeof(struct slot_config); i++)
		printf("addr: 0x%02x, config[%02d]: 0x%02x 0x%02x, config[%02d]: 0x%02x 0x%02x\n",
		       slot_configs[i].address,
		       2*i, slot_configs[i].value[0], slot_configs[i].value[1],
		       (2*i)+1, slot_configs[i].value[2], slot_configs[i].value[3]);

	return STATUS_OK;
}
